# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
sv:
  languageCode: sv
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#en:
#  languageCode: en-gb
#  contentDir: content/en
#  title: English website title...
#  params:
#    description: Site description in English...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
