# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Om föreningen
    url: om-foreningen-och-styrelsen
    weight: 10
  - name: Bli medlem
    url: post
    weight: 20
  - name: Event
    url: event
    weight: 30
  - name: Västerbottens turfklassiker
    url: publication
    weight: 40
  - name: Vandringspokalen
    url: publication
    weight: 50
  - name: Profilkläder
    url: publication
    weight: 60
  - name: Vad är Turf?
    url: publication
    weight: 70
  - name: Kontakt
    url: contact
    weight: 80
  - name: Turfgame.com
    url: publication
    weight: 90
